# Site settings
title: Dimas Abreu Archanjo Dutra
email: dimasad@ufmg.br
description: >
  Professor do Departamento de Engenharia Mecânica da Universidade Federal
  de Minas Gerais.
baseurl: ""
url: "http://dimasad.github.io"

# Build settings
markdown: kramdown
permalink: pretty
